USE [master]
GO

/****** Object:  Database [Teretana]    Script Date: 5/18/2017 8:32:43 PM ******/
CREATE DATABASE [Teretana]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Teretana', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\Teretana.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Teretana_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\Teretana_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [Teretana] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Teretana].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Teretana] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Teretana] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Teretana] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Teretana] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Teretana] SET ARITHABORT OFF 
GO

ALTER DATABASE [Teretana] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Teretana] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Teretana] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Teretana] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Teretana] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Teretana] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Teretana] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Teretana] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Teretana] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Teretana] SET  ENABLE_BROKER 
GO

ALTER DATABASE [Teretana] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Teretana] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Teretana] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Teretana] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Teretana] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Teretana] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Teretana] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Teretana] SET RECOVERY FULL 
GO

ALTER DATABASE [Teretana] SET  MULTI_USER 
GO

ALTER DATABASE [Teretana] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Teretana] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Teretana] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Teretana] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Teretana] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Teretana] SET QUERY_STORE = OFF
GO

USE [Teretana]
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [Teretana] SET  READ_WRITE 
GO

